#!/bin/bash
clear
echo "-----------------------------------------------------"
echo "-- COMPILING...                                    --"
echo "-----------------------------------------------------"
echo ""
gcc ma.c -lSDL2 -lSDL2_mixer -lSDL2_image -lSDL2_net -lGL -o ma.app
